import type { LanguageCode } from "./languages";

export const EXAM_STRINGS: Record<
  LanguageCode,
  {
    fillBlankLabel: string;
    translateLabel: string;
    typeAnswerPlaceholder: string;
    submitExam: string;
    passedTitle: string;
    failedTitle: string;
    yourScore: string;
    reviewTopics: string;
    retakeExam: string;
    continueBtn: string;
    startExam: string;
    examIntro: string;
    back: string;
    next: string;
    checkAnswer: string;
    correctFeedback: string;
    incorrectFeedback: string;
  }
> = {
  en: {
    fillBlankLabel: "Fill in the blank",
    translateLabel: "Translate this phrase",
    typeAnswerPlaceholder: "Type your answer...",
    submitExam: "Submit exam",
    passedTitle: "You passed!",
    failedTitle: "Not quite — try again",
    yourScore: "Your score:",
    reviewTopics: "Review these topics before retaking:",
    retakeExam: "Retake exam",
    continueBtn: "Continue to Stage 3",
    startExam: "Start exam",
    examIntro: "20 questions covering everything from Stage 1. You need 70% to pass.",
    back: "Back",
    next: "Next",
    checkAnswer: "Check answer",
    correctFeedback: "Correct!",
    incorrectFeedback: "Incorrect. Correct answer:",
  },
  es: {
    fillBlankLabel: "Completa el espacio",
    translateLabel: "Traduce esta frase",
    typeAnswerPlaceholder: "Escribe tu respuesta...",
    submitExam: "Enviar examen",
    passedTitle: "¡Aprobaste!",
    failedTitle: "Casi — inténtalo de nuevo",
    yourScore: "Tu puntuación:",
    reviewTopics: "Repasa estos temas antes de reintentar:",
    retakeExam: "Repetir examen",
    continueBtn: "Continuar a la Etapa 3",
    startExam: "Comenzar examen",
    examIntro: "20 preguntas sobre todo lo de la Etapa 1. Necesitas 70% para aprobar.",
    back: "Atrás",
    next: "Siguiente",
    checkAnswer: "Comprobar respuesta",
    correctFeedback: "¡Correcto!",
    incorrectFeedback: "Incorrecto. Respuesta correcta:",
  },
  fr: {
    fillBlankLabel: "Complétez le blanc",
    translateLabel: "Traduisez cette phrase",
    typeAnswerPlaceholder: "Tapez votre réponse...",
    submitExam: "Soumettre l'examen",
    passedTitle: "Vous avez réussi !",
    failedTitle: "Pas tout à fait — réessayez",
    yourScore: "Votre score :",
    reviewTopics: "Révisez ces sujets avant de recommencer :",
    retakeExam: "Repasser l'examen",
    continueBtn: "Passer à l'étape 3",
    startExam: "Commencer l'examen",
    examIntro: "20 questions couvrant toute l'étape 1. Il faut 70 % pour réussir.",
    back: "Précédent",
    next: "Suivant",
    checkAnswer: "Vérifier la réponse",
    correctFeedback: "Correct !",
    incorrectFeedback: "Incorrect. Bonne réponse :",
  },
  de: {
    fillBlankLabel: "Lücke ausfüllen",
    translateLabel: "Übersetze diesen Ausdruck",
    typeAnswerPlaceholder: "Antwort eingeben...",
    submitExam: "Prüfung abschicken",
    passedTitle: "Bestanden!",
    failedTitle: "Noch nicht — versuch's noch einmal",
    yourScore: "Deine Punktzahl:",
    reviewTopics: "Wiederhole diese Themen vor dem nächsten Versuch:",
    retakeExam: "Prüfung wiederholen",
    continueBtn: "Weiter zu Stufe 3",
    startExam: "Prüfung starten",
    examIntro: "20 Fragen zu allem aus Stufe 1. Du brauchst 70 %, um zu bestehen.",
    back: "Zurück",
    next: "Weiter",
    checkAnswer: "Antwort prüfen",
    correctFeedback: "Richtig!",
    incorrectFeedback: "Falsch. Richtige Antwort:",
  },
  ar: {
    fillBlankLabel: "أكمل الفراغ",
    translateLabel: "ترجم هذه العبارة",
    typeAnswerPlaceholder: "اكتب إجابتك...",
    submitExam: "إرسال الامتحان",
    passedTitle: "لقد نجحت!",
    failedTitle: "ليس تمامًا — حاول مرة أخرى",
    yourScore: "نتيجتك:",
    reviewTopics: "راجع هذه المواضيع قبل إعادة المحاولة:",
    retakeExam: "إعادة الامتحان",
    continueBtn: "الانتقال إلى المرحلة 3",
    startExam: "ابدأ الامتحان",
    examIntro: "20 سؤالاً يغطي كل ما جاء في المرحلة 1. تحتاج إلى 70% للنجاح.",
    back: "رجوع",
    next: "التالي",
    checkAnswer: "تحقق من الإجابة",
    correctFeedback: "إجابة صحيحة!",
    incorrectFeedback: "إجابة خاطئة. الإجابة الصحيحة:",
  },
  zh: {
    fillBlankLabel: "填空",
    translateLabel: "翻译这个短语",
    typeAnswerPlaceholder: "输入你的答案...",
    submitExam: "提交考试",
    passedTitle: "你通过了！",
    failedTitle: "差一点——再试一次",
    yourScore: "你的得分：",
    reviewTopics: "重考前请复习这些主题：",
    retakeExam: "重新考试",
    continueBtn: "进入第三阶段",
    startExam: "开始考试",
    examIntro: "20道题，涵盖第一阶段的全部内容。需要达到70%才能通过。",
    back: "上一题",
    next: "下一题",
    checkAnswer: "检查答案",
    correctFeedback: "正确！",
    incorrectFeedback: "不正确。正确答案：",
  },
  pt: {
    fillBlankLabel: "Complete a lacuna",
    translateLabel: "Traduza esta frase",
    typeAnswerPlaceholder: "Digite sua resposta...",
    submitExam: "Enviar prova",
    passedTitle: "Você passou!",
    failedTitle: "Quase — tente novamente",
    yourScore: "Sua pontuação:",
    reviewTopics: "Revise estes tópicos antes de tentar novamente:",
    retakeExam: "Refazer prova",
    continueBtn: "Continuar para o Estágio 3",
    startExam: "Começar prova",
    examIntro: "20 perguntas cobrindo tudo do Estágio 1. Você precisa de 70% para passar.",
    back: "Voltar",
    next: "Próxima",
    checkAnswer: "Verificar resposta",
    correctFeedback: "Correto!",
    incorrectFeedback: "Incorreto. Resposta correta:",
  },
  ja: {
    fillBlankLabel: "空欄を埋めてください",
    translateLabel: "このフレーズを訳してください",
    typeAnswerPlaceholder: "答えを入力...",
    submitExam: "試験を提出",
    passedTitle: "合格しました！",
    failedTitle: "もう少しです — もう一度挑戦してください",
    yourScore: "あなたのスコア：",
    reviewTopics: "再挑戦する前にこれらのトピックを復習してください：",
    retakeExam: "試験をやり直す",
    continueBtn: "ステージ3へ進む",
    startExam: "試験を始める",
    examIntro: "ステージ1の内容を網羅する20問です。合格には70%が必要です。",
    back: "戻る",
    next: "次へ",
    checkAnswer: "答えを確認",
    correctFeedback: "正解！",
    incorrectFeedback: "不正解。正解は：",
  },
};
